apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: REPLACEME-eks-cluster
  region: us-east-1
  version: "1.16"

status:
  endpoint: private

nodeGroups:
  - name: cloudbees-core-masters
    instanceType: r5.xlarge
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: masters
    }
    taints: {
      partition: masters:NoSchedule
    }
    iam:
      withAddonPolicies:
        autoScaler: true
        efs: true
  - name: cloudbees-core-regular
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    privateNetworking: true
    labels: {
      partition: regular-agents
    }
    iam:
      withAddonPolicies:
        autoScaler: true

vpc:
  id: "REPLACEME-vpcid"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: false
  subnets:
    private:
      us-east-1a:
        id: "REPLACEME-1a"
      us-east-1b:
        id: "REPLACEME-1b"
      us-east-1c:
        id: "REPLACEME-1c"
